"""NON-RIGOROUS HELPER (not part of the proof): computes the trial-function
coefficients used by cert_E.py by a floating-point Rayleigh-Ritz computation in
the odd E-type sector, converts them EXACTLY to rationals (binary64 values), and
writes trial_coeffs.json.  Any coefficients whatsoever give a valid certificate;
floating point only influences how sharp the resulting enclosures are.

    python3 make_trial_coeffs.py [K]      (default K = 25)
"""
import json
import sys
import numpy as np
from numpy.polynomial.legendre import leggauss
from cert_E import sector_degrees


# ---------------------------------------------------------------- float Ritz
def float_ritz(K, q=None):
    ks = sector_degrees(K)
    if q is None:
        q = 2 * K + 10
    x, w = leggauss(q)
    t = (x + 1) / 2; w = w / 2
    V = [complex(0, 1), complex(-np.sqrt(3) / 2, -0.5), complex(np.sqrt(3) / 2, -0.5)]
    H, Hn, W = [], [], []
    for e in range(3):
        a, b = V[e], V[(e + 1) % 3]
        d = b - a; L = abs(d); nu = -1j * d / L
        z = a + t * d
        rows, drows = [], []
        for k in ks:
            ak = 1 if k % 2 == 1 else -1j
            rows.append((ak * z**k).real)
            drows.append((ak * k * z**(k - 1) * nu).real)
        H.append(np.array(rows).T); Hn.append(np.array(drows).T); W.append(w * L)
    H = np.vstack(H); Hn = np.vstack(Hn); W = np.concatenate(W)
    B = H.T @ (W[:, None] * H)
    A = H.T @ (W[:, None] * Hn); A = (A + A.T) / 2
    from scipy.linalg import eigh
    ev, vec = eigh(A, B)
    c = vec[:, 0]
    c = c / c[0]                       # normalise coefficient of z^1 to 1
    return ks, c, ev[0]


# ---------------------------------------------------------------- exact parts
def to_rational_string(x):
    """exact rational value of a binary64 float"""
    p, q = float(x).as_integer_ratio()
    return f"{p}/{q}"



if __name__ == "__main__":
    K = int(sys.argv[1]) if len(sys.argv) > 1 else 25
    ks, c, ev0 = float_ritz(K)
    data = {"description": "Exact rational coefficients c_k of the trial function Re sum_k c_k a_k z^k "
                           "(a_k = 1 for odd k, -i for even k) on the equilateral triangle with vertices "
                           "i, exp(7 pi i/6), exp(-pi i/6). Generated by make_trial_coeffs.py (floating-point "
                           "Ritz, non-rigorous); used verbatim by cert_E.py.",
            "float_ritz_value": repr(float(ev0)),
            "degrees": ks,
            "coefficients": [to_rational_string(x) for x in c]}
    with open("trial_coeffs.json", "w") as f:
        json.dump(data, f, indent=1)
        f.write("\n")
    print(f"wrote trial_coeffs.json: K={K}, {len(ks)} coefficients, float Ritz value {ev0:.15f}")
