#!/usr/bin/env python3
"""Exact finite regression checks for v0.3; not a proof of a limiting law.

Python standard library only. All acceptance checks use Fraction arithmetic.
Trigonometric data are generated by the rational parametrization
cot(theta)=(1-t*t)/(2*t), csc(theta)=(1+t*t)/(2*t), t != 0.
"""

from fractions import Fraction as F
from itertools import product
from random import Random


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def sign(x):
    return int(x > 0) - int(x < 0)


def phase(t):
    return (1 - t*t)/(2*t), (1 + t*t)/(2*t)


def h(a, c, r):
    return F(sign(a), 2) * (
        1 - sign(c[0] + c[1] + r*c[2]) *
        (sign(c[0]) + sign(c[1]) + sign(r*c[2])))


def positive_index(matrix):
    """Exact symmetric elimination, independently of the manuscript's pivots."""
    a = [list(row) for row in matrix]
    result = 0
    while a:
        k = next((i for i in range(len(a)) if a[i][i]), None)
        if k is None:
            pair = next(((i, j) for i in range(len(a))
                         for j in range(i) if a[i][j]), None)
            if pair is None:
                break
            i, j = pair
            others = [k for k in range(len(a)) if k not in pair]
            b = a[i][j]
            a = [[a[k][l] - (a[k][i]*a[j][l] + a[k][j]*a[i][l])/b
                  for l in others] for k in others]
            result += 1  # [[0,b],[b,0]] has one positive eigenvalue.
        else:
            others = [i for i in range(len(a)) if i != k]
            pivot = a[k][k]
            result += int(pivot > 0)
            a = [[a[i][j] - a[i][k]*a[k][j]/pivot
                  for j in others] for i in others]
    return result


def check_sign_average():
    count = 0
    for c1, c2, c3, rho in product([F(1), F(3, 2), F(7, 3), F(5)], repeat=4):
        if rho*c3 in (abs(c1-c2), c1+c2):
            continue  # The manuscript asserts this off null boundary sets.
        for delta in (-1, 1):
            average = sum(h(F(1), [s1*c1, s2*c2, s3*c3], delta*rho)**2
                          for s1, s2, s3 in product((-1, 1), repeat=3))/8
            triangle = abs(c1-c2) < rho*c3 < c1+c2
            require(average == F(1, 2) - F(int(triangle), 4),
                    'conditional second-moment identity')
            count += 1
    return count


def check_graphs():
    rng = Random(11420261005)
    candidates = [F(s*n, d) for s in (-1, 1) for n in range(1, 9)
                  for d in range(1, 8)]
    counts = []
    for m in (3, 4, 7, 12):
        accepted = 0
        for _ in range(120):
            modules = [[phase(rng.choice(candidates)) for _ in range(3)]
                       for _ in range(m)]
            aa = [sum(x for x, c in module) for module in modules]
            if 0 in aa:
                continue
            pp = [module[0][1]+module[1][1] for module in modules]
            qq = [module[2][1] for module in modules]
            u = sum(p*q/a for p, q, a in zip(pp, qq, aa))
            t = sum(-module[2][0]+q*q/a
                    for module, q, a in zip(modules, qq, aa))
            if not u or not t:
                continue
            r = -u/t
            ff = [(p+r*q)/a for p, q, a in zip(pp, qq, aa)]
            lam = sum(-module[0][0]-module[1][0]+p*p/a
                      for module, p, a in zip(modules, pp, aa))
            g = lam-u*u/t
            if not g or 0 in ff:
                continue
            # Core matrix with u deleted, in order (v,w1,...,wm).
            matrix = [[F(0) for _ in range(m+1)] for _ in range(m+1)]
            matrix[0][0] = -sum(module[2][0] for module in modules)
            for i, (module, a, q) in enumerate(zip(modules, aa, qq), 1):
                matrix[i][i] = -a
                matrix[0][i] = matrix[i][0] = q
                for x, c in module:
                    require(c*c == 1+x*x, 'phase parametrization')
            qcount = sum(int(f*module[0][1] < 0) + int(f*module[1][1] < 0)
                         + int(r*f*module[2][1] < 0)
                         for f, module in zip(ff, modules))
            surplus = qcount-positive_index(matrix)
            formula = F(2*m-1, 2) + sum(h(a, [c for x, c in module], r)
                                        for a, module in zip(aa, modules)) - F(sign(t), 2)
            require(formula == surplus, 'surplus sign/inertia identity')
            require(0 <= surplus <= 2*m-1, 'surplus support')
            # These equations verify the eliminated core vertex vector.
            require(u+t*r == 0, 'v boundary equation')
            for a, p, q, f in zip(aa, pp, qq, ff):
                require(-a*f+p+r*q == 0, 'module boundary equation')
            # cot(theta0)=-1/g. The pendant count equals its positive pivot.
            require(int(-g < 0) == int(1/g > 0), 'pendant cancellation')
            accepted += 1
        require(accepted >= 100, 'too few nonexceptional exact graph checks')
        counts.append((m, accepted))
    return counts


def check_response():
    count = 0
    for s, x in product([F(-4), F(-2, 3), F(0), F(3, 2), F(7)], repeat=2):
        if s+x:
            require(-x+(1+x*x)/(s+x) == (1-s*x)/(s+x),
                    'boundary tangent identity')
            require((s+x)**2+(1-s*x)**2 == (1+s*s)*(1+x*x),
                    'boundary secant identity')
            count += 1
    for x, y in product([F(-5), F(-1, 2), F(0), F(2, 3), F(4)], repeat=2):
        require((2+x*x+y*y)/((1+x*x)*(1+y*y)) ==
                1/(1+x*x)+1/(1+y*y), 'W second-moment integrand identity')
    return count


def main():
    print('Exact rational finite checks; these do not verify spectral or distributional limits.')
    for matrix, expected in (([[F(0)]], 0), ([[F(2)]], 1), ([[F(-3)]], 0),
                             ([[F(0), F(2)], [F(2), F(0)]], 1),
                             ([[F(2), F(1)], [F(1), F(2)]], 2)):
        require(positive_index(matrix) == expected, 'inertia algorithm control')
    print('Sign-average cases:', check_sign_average())
    print('Graph sign/inertia cases (m, accepted):', check_graphs())
    print('Boundary-response cases:', check_response())
    print('PASS: all exact finite regression checks')


if __name__ == '__main__':
    main()
